### ISSUE TITLE
Get reward issue

### ISSUE THREAD

**Issue by DavidKristen11** [ArteonToken/mining-issues#3]
issue where the “get reward” button is dead ? Usually has the little hand icon when you hover over and works fine but i has to do a delete cookies and cache and now it’s like having a dead link. Restarted pc and still not working ? Weird as the deactivate card button still works of I wanted to use that but not the other button. Also tried on chrome and Firefox and same error?. Is there a different website to try it on ?

**Comment by DavidKristen11** [comment]
I’ve also tried refreshing chrome , deleting all cookies / cache etc and also connected different wallets and same issue. All other buttons work fine  ( activate / deactivate card, buy Arteon token buttons etc ) all except the get rewards button.

**Comment by VandeurenGlenn** [comment]
Hi @DavidKristen11 This was bacause of an update, we wanted to protect users to not pay more fees then rewards they got.
Note, we switched to Binance Smartchain and I removed the limitation.
